### ISSUE TITLE
make_digital_object doesn't replicate the digital object file list

### ISSUE THREAD

**Issue by jackflaps** [duspeccoll/astools#2]
Current behavior: if, when processing a folder, the script encounters files that do not exist in the folder but have digital object component records in ArchivesSpace, it does not delete the old records
Desired behavior: Asks the user if they wish to delete component records for files that do not exist in the folder being processed

**Comment by Falicey** [comment]
Will now keep a hidden list of items to be deleted, and will prompt the user to delete them when processing.
