### ISSUE TITLE
make_digital_object should prompt a user to log in if no .archivessnake.yml file is found

### ISSUE THREAD

**Issue by duspeccoll** [duspeccoll/astools#3]
Users may not have an .archivessnake.yml file set up to log into the ArchivesSpace backend when they install this script for the first time; the script should detect .archivessnake.yml and prompt for an API URL/login/password if one is not found

**Comment by Falicey** [comment]
no longer uses .archivesspace.yml, instead uses local json file.  popup window will ask for credentials and create the json file if it doesn't exist.
