### ISSUE TITLE
make_digital_object should indicate no changes and not post when no changes are made

### ISSUE THREAD

**Issue by jackflaps** [duspeccoll/astools#4]
Current behavior: script posts changes to API even if the record is unchanged, and posts "Updated" to the log
Desired behavior: Records with no changes have update flag set to 'false'; if no updates are detected, the record is not posted and a "no change" message is sent to the logs

**Comment by Falicey** [comment]
Now distinguishes between new records, existing records that haven't been changed, and existing records that have been changed, and will update or not update accordingly.
